apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: schedule greeting

on:
  push:
    branches:
      - "**"
  schedule:
    - cron: "6,12,18,24,30,36,42,48,54 * * * *"

permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write

jobs:
  greet:
    steps:
    - name: greet
      uses: docker://alpine:3.20
      run: echo "hello"
